-- MySQL Script generated by MySQL Workbench
-- 04/19/17 21:43:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbcafeteria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbcafeteria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbcafeteria` DEFAULT CHARACTER SET utf8 ;
USE `dbcafeteria` ;

-- -----------------------------------------------------
-- Table `dbcafeteria`.`tipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcafeteria`.`tipoUsuario` (
  `clavetipo` INT NOT NULL AUTO_INCREMENT,
  `desc_tipo` CHAR(30) NOT NULL,
  PRIMARY KEY (`clavetipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcafeteria`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcafeteria`.`usuario` (
  `clave_us` VARCHAR(50) NOT NULL,
  `nombre_us` CHAR(30) NOT NULL,
  `apellido_p_us` CHAR(20) NOT NULL,
  `apellido_m_us` CHAR(20) NOT NULL,
  `password` VARCHAR(10) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `clavetipo` INT NOT NULL,
  PRIMARY KEY (`clave_us`),
  INDEX `fk_usuario_tipoUsuario1_idx` (`clavetipo` ASC),
  CONSTRAINT `fk_usuario_tipoUsuario1`
    FOREIGN KEY (`clavetipo`)
    REFERENCES `dbcafeteria`.`tipoUsuario` (`clavetipo`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcafeteria`.`monedero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcafeteria`.`monedero` (
  `saldoMonedero` DECIMAL NOT NULL,
  `clave_us` VARCHAR(50) NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaTermino` DATE NOT NULL,
  `claveMonedero` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`claveMonedero`),
  INDEX `fk_monedero_usuario_idx` (`clave_us` ASC),
  CONSTRAINT `fk_monedero_usuario`
    FOREIGN KEY (`clave_us`)
    REFERENCES `dbcafeteria`.`usuario` (`clave_us`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcafeteria`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcafeteria`.`producto` (
  `claveProducto` INT NOT NULL AUTO_INCREMENT,
  `nombreProducto` CHAR(20) NOT NULL,
  `precioProducto` DECIMAL NOT NULL,
  `descripcion` MEDIUMTEXT NULL,
  `imagen` MEDIUMBLOB NOT NULL,
  `estado` CHAR(20) NOT NULL,
  PRIMARY KEY (`claveProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcafeteria`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcafeteria`.`pedidos` (
  `clavePedido` INT NOT NULL AUTO_INCREMENT,
  `fechaPedido` DATE NOT NULL,
  `montoPedido` DECIMAL(10,2) NOT NULL,
  `clave_us` VARCHAR(50) NOT NULL,
  `claveProducto` INT NOT NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`clavePedido`),
  INDEX `FK_pedidos_usuario_idx` (`clave_us` ASC),
  INDEX `FK_pedidos_producto_idx` (`claveProducto` ASC),
  CONSTRAINT `FK_pedidos_usuario`
    FOREIGN KEY (`clave_us`)
    REFERENCES `dbcafeteria`.`usuario` (`clave_us`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_pedidos_producto`
    FOREIGN KEY (`claveProducto`)
    REFERENCES `dbcafeteria`.`producto` (`claveProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcafeteria`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcafeteria`.`ventas` (
  `claveVenta` INT NOT NULL AUTO_INCREMENT,
  `clave_us` VARCHAR(50) NOT NULL,
  `clavePedido` INT NULL,
  `claveProducto` INT NULL,
  `fechaHora_venta` DATETIME NOT NULL,
  `totalVenta` DECIMAL NULL,
  PRIMARY KEY (`claveVenta`),
  INDEX `FK_ventas_usuario_idx` (`clave_us` ASC),
  INDEX `FK_ventas__pedido_idx` (`clavePedido` ASC),
  INDEX `FK_ventas_producto_idx` (`claveProducto` ASC),
  CONSTRAINT `FK_ventas_usuario`
    FOREIGN KEY (`clave_us`)
    REFERENCES `dbcafeteria`.`usuario` (`clave_us`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ventas__pedido`
    FOREIGN KEY (`clavePedido`)
    REFERENCES `dbcafeteria`.`pedidos` (`clavePedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ventas_producto`
    FOREIGN KEY (`claveProducto`)
    REFERENCES `dbcafeteria`.`producto` (`claveProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcafeteria`.`detalleVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcafeteria`.`detalleVenta` (
  `clavedetalle_venta` INT NOT NULL AUTO_INCREMENT,
  `claveVenta` INT NOT NULL,
  `cantidadVendida_pdcto` INT NOT NULL,
  `claveProducto` INT NOT NULL,
  PRIMARY KEY (`clavedetalle_venta`),
  INDEX `fk_detalleVenta_producto_idx` (`claveProducto` ASC),
  INDEX `fk_detalleVenta_ventas_idx` (`claveVenta` ASC),
  CONSTRAINT `fk_detalleVenta_producto`
    FOREIGN KEY (`claveProducto`)
    REFERENCES `dbcafeteria`.`producto` (`claveProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalleVenta_ventas`
    FOREIGN KEY (`claveVenta`)
    REFERENCES `dbcafeteria`.`ventas` (`claveVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcafeteria`.`historialRecargas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcafeteria`.`historialRecargas` (
  `claveRecarga` INT NOT NULL AUTO_INCREMENT,
  `fechaRecarga` DATE NOT NULL,
  `cantidadRecarga` DECIMAL NOT NULL,
  `claveMonedero` VARCHAR(50) NULL,
  PRIMARY KEY (`claveRecarga`),
  INDEX `fk_historialRecargas_monedero_idx` (`claveMonedero` ASC),
  CONSTRAINT `fk_historialRecargas_monedero`
    FOREIGN KEY (`claveMonedero`)
    REFERENCES `dbcafeteria`.`monedero` (`claveMonedero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcafeteria`.`detalleProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcafeteria`.`detalleProducto` (
  `claveDetalle_pdcto` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`claveDetalle_pdcto`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
